---
title: "Untitled"
author: "Erlangga"
date: "2025-10-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
if (!require("maps")) install.packages("maps")
library(maps)

asc <- read.csv("ASC.csv")
aip_detail <- read.csv("AIP_Detail.csv")
aip_program <- read.csv("AIP_program.csv")

asc$Type <- "ASC Site"
aip_detail$Type <- "AIP Detail Site"
aip_program$Type <- "AIP Program Site"

sites <- rbind(
  asc[, c("Longitude", "Latitude", "Type")],
  aip_detail[, c("Longitude", "Latitude", "Type")],
  aip_program[, c("Longitude", "Latitude", "Type")]
)

site_colors <- c(
  "ASC Site" = "#7b3294",
  "AIP Detail Site" = "#008080",
  "AIP Program Site" = "#ffe047"
)
pt_colors <- site_colors[as.character(sites$Type)]

# Map boundaries for regional context
min_lon <- 90
max_lon <- 150
min_lat <- -15
max_lat <- 15

# Uncomment below for PDF output
pdf("all_sites_map_wide.pdf", width = 10, height = 7)

old_par <- par(no.readonly = TRUE)
par(xaxs = "i", yaxs = "i")

plot(NA, xlim = c(min_lon, max_lon), ylim = c(min_lat, max_lat),
     type = "n", xlab = "", ylab = "", axes = FALSE)
rect(min_lon, min_lat, max_lon, max_lat, col = "lightblue", border = NA)

map("world", xlim = c(min_lon, max_lon), ylim = c(min_lat, max_lat),
    col = "grey85", fill = TRUE, add = TRUE)

abline(v = seq(min_lon, max_lon, 4), col = "grey70", lty = 3)
abline(h = seq(min_lat, max_lat, 4), col = "grey70", lty = 3)

axis(1, at = seq(min_lon, max_lon, 4),
     labels = paste0(seq(min_lon, max_lon, 4), "°E"), cex.axis = 0.7)
axis(2, at = seq(min_lat, max_lat, 4),
     labels = paste0(abs(seq(min_lat, max_lat, 4)),
                     ifelse(seq(min_lat, max_lat, 4) < 0, "°S", "°N")), cex.axis = 0.7)

points(sites$Longitude, sites$Latitude,
       pch = 21, bg = pt_colors, col = pt_colors, cex = 1.5)

legend("bottomright",
       legend = names(site_colors),
       pt.bg = site_colors,
       pch = 21, col = "black", cex = 0.8, bg = "white")

scalebar_length <- 200
scalebar_x <- min_lon + 1
scalebar_y <- min_lat + 1
rect(scalebar_x, scalebar_y, scalebar_x + 2, scalebar_y + 0.2, col = "black")
text(scalebar_x + 1, scalebar_y - 0.5, paste0(scalebar_length, " km"),
     adj = 0.3, cex = 0.5)

north_x <- max_lon - 1
north_N_y <- max_lat - 0.8
text(north_x, north_N_y, "N", cex = 0.7, font = 12)

par(old_par)
# dev.off() # Uncomment if saving to PDF

```

